# Generated by Django 4.2.7 on 2023-11-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_remove_order_id_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
