# Generated by Django 4.2.7 on 2023-11-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
